### ISSUE TITLE
gophish Templates

### ISSUE THREAD

**Issue by Hemza** [gophish/hub#1]
Dear developpers ,

i'm looking for gophish templates , can't any one help me

thank you

**Comment by krasian-zz** [comment]
This has obviously been open for awhile.  as there is a /templates that doesn't have anything and it appears we have somewhat of an active community, can we upload to templates or even have some sort of repository for them?  I've got some I wouldn't mind sharing and would also love to see what others have.

**Comment by jordan-wright** [comment]
Closing since we're rebranding this repo. More information can be found in https://github.com/gophish/gophish/issues/1589.
