### ISSUE TITLE
Templates and Trademark Infringement.

### ISSUE THREAD

**Issue by rfdevere** [gophish/hub#2]
I am willing to lend a hand with making templates up, if it's of use. The issues of trademark infringement have actually taken down previous online phishing software as (for obvious reasons) they viewed it as damaging to their brands. It's an issue that has to be overcome though if templates are going to be provided. Does someone just float a torrent file of these unofficial templates about? or is there a better way that might significantly reduce the real life look of these portals - by removing brands.

Either way let me know and I can make 20+ covering SSL VPN's and Popular services. What we do with them then is another thing.

**Comment by thesle3p** [comment]
I would post them using a throw away github account, or like you said as a torrent. Though to be honest I have not heard of phishing templates used in user awareness training or pen testing resulting in trademark litigation.

**Comment by rfdevere** [comment]
Or start a company in Panama to publish them ;-)

On Thu, Apr 7, 2016 at 3:36 PM, thesle3p notifications@github.com wrote:

> I would post them using a throw away github account, or like you said as a
> torrent. Though to be honest I have not heard of phishing templates used in
> user awareness training or pen testing resulting in trademark litigation.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gophish/templates/issues/2#issuecomment-206934474

## 

_Richard De Vere_
_Principal Consultant_

_Tel:_ +44 754 6655448
_Web:_ TheAntiSocialEngineer.com
_Email:_ FrontDesk@TheAntiSocialEngineer.com
_Twitter:_ @AntiSocial_Eng

The AntiSocial Engineer Ltd is a limited company registered in England and
Wales. Company Registration No. 09367111 Registered Office: 4 Capel Street,
Huddersfield, HD6 3AJ This message contains confidential information and is
intended only for AntiSocial Engineer customers. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The AntiSocial Engineer Ltd cannot accept liability for
any errors or omissions in the contents of this message, which may arise as
a result of e-mail transmission. Please note that The AntiSocial Engineer
Ltd may monitor, analyse and archive email traffic, data and the content of
email for the purposes of security, legal compliance and staff training.

**Comment by thesle3p** [comment]
Either way the main thing holding gophish back IMO is the lack of a repo of
templates.

**Comment by rfdevere** [comment]
What would be the exact best format to host these?

On Thu, Apr 7, 2016 at 4:01 PM, thesle3p notifications@github.com wrote:

> Either way the main thing holding gophish back IMO is the lack of a repo of
> templates.
> On Apr 7, 2016 10:59 AM, "Richard De Vere" notifications@github.com
> wrote:
> 
> > Or start a company in Panama to publish them ;-)
> > 
> > On Thu, Apr 7, 2016 at 3:36 PM, thesle3p notifications@github.com
> > wrote:
> > 
> > > I would post them using a throw away github account, or like you said
> > > as
> > > a
> > > torrent. Though to be honest I have not heard of phishing templates
> > > used
> > > in
> > > user awareness training or pen testing resulting in trademark
> > > litigation.
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gophish/templates/issues/2#issuecomment-206934474
> > 
> > ## 
> > 
> > _Richard De Vere_
> > _Principal Consultant_
> > 
> > _Tel:_ +44 754 6655448
> > _Web:_ TheAntiSocialEngineer.com
> > _Email:_ FrontDesk@TheAntiSocialEngineer.com
> > _Twitter:_ @AntiSocial_Eng
> > 
> > The AntiSocial Engineer Ltd is a limited company registered in England
> > and
> > Wales. Company Registration No. 09367111 Registered Office: 4 Capel
> > Street,
> > Huddersfield, HD6 3AJ This message contains confidential information and
> > is
> > intended only for AntiSocial Engineer customers. E-mail transmission
> > cannot
> > be guaranteed to be secure or error-free as information could be
> > intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
> > contain viruses. The AntiSocial Engineer Ltd cannot accept liability for
> > any errors or omissions in the contents of this message, which may arise
> > as
> > a result of e-mail transmission. Please note that The AntiSocial Engineer
> > Ltd may monitor, analyse and archive email traffic, data and the content
> > of
> > email for the purposes of security, legal compliance and staff training.
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/gophish/templates/issues/2#issuecomment-206942244
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gophish/templates/issues/2#issuecomment-206942794

## 

_Richard De Vere_
_Principal Consultant_

_Tel:_ +44 754 6655448
_Web:_ TheAntiSocialEngineer.com
_Email:_ FrontDesk@TheAntiSocialEngineer.com
_Twitter:_ @AntiSocial_Eng

The AntiSocial Engineer Ltd is a limited company registered in England and
Wales. Company Registration No. 09367111 Registered Office: 4 Capel Street,
Huddersfield, HD6 3AJ This message contains confidential information and is
intended only for AntiSocial Engineer customers. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The AntiSocial Engineer Ltd cannot accept liability for
any errors or omissions in the contents of this message, which may arise as
a result of e-mail transmission. Please note that The AntiSocial Engineer
Ltd may monitor, analyse and archive email traffic, data and the content of
email for the purposes of security, legal compliance and staff training.

**Comment by thesle3p** [comment]
I would make a github repo with a txt saying you don't claim ownership of any of the brands used in the templates etc and hope for the best. I am doubtful any litigation will come from templates to be honest either way a disclaimer would limit your liability (a little bit). 

-----Original Message-----

**Comment by rfdevere** [comment]
Agreed, @jordan-wright in my down time i'm going to start compiling some good portals and email templates, do you want to arrange another Skype? and I can check i've got the right idea before this step.

**Comment by thesle3p** [comment]
Any updates?

**Comment by Raytri3** [comment]
Of course the "name brand" templates like LinkedIn, Facebook, etc. will cause problems; however there is no reason we couldn't create and share other "public" formats. For example a Fax receipt, "drobbox" type solution, secure email, birthday wishes (always a favorite), etc. Is there an easy way to export them?

**Comment by rfdevere** [comment]
https://github.com/rfdevere/templates would be a small start, if people want to dump stuff there then we can get this collection good enough to be pulled in.

**Comment by krasian-zz** [comment]
I know this is an old topic, but for those worried about copyrights, I found this on KnowBe4's web site related to the exact issue.  If we aren't going to contribute landing pages and email templates here, then I suggest we do it on the site Richard set up.

[https://www.knowbe4.com/fud](https://www.knowbe4.com/fud)

**Comment by rfdevere** [comment]
Quick addition. 

This was posted a a while ago, since then I have had no issues using named templates with all clients. In the UK this is copyright exempt because it is educational.

I would be happy to add a few common templates in the following days, but also be aware Jordan has made his choice as per affiliation with this - and rightly so, some issues *may* arise.

Especially as gophish is so popular as a base in the UK phishing market it would be great to stick to the aims of the project and give people the resources for free...

**Comment by jordan-wright** [comment]
Closing since we're rebranding this repo. More information can be found in https://github.com/gophish/gophish/issues/1589 (@rfdevere I'd love your feedback on that proposal!)
